name: Tests del Plugin FacturaScripts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      # testear github actions
      - addGithubActions

concurrency:
  # que se cancele el test actual si se hace otro commit en la misma rama
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Tests en mysql con PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.0', '8.1']

    env:
      NOMBRE_PLUGIN: "Tickets"

    steps:
      - name: Instalar PHP y extensiones
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: json, fileinfo, simplexml, zip, dom, pdo, pdo_mysql, mysql, mysqli, pgsql, pdo_pgsql, bcmath, gd, curl, soap
          tools: composer
          coverage: none

      - name: Montar base de datos
        uses: shogo82148/actions-setup-mysql@v1
        with:
          distribution: "mysql"
          mysql-version: "8.0"
          root-password: "root"

      - name: Crear base de datos
        run: 'mysql -u root -proot -e "CREATE DATABASE facturascripts CHARACTER SET utf8 COLLATE utf8_bin;"'

      - name: Clonar FacturaScripts
        uses: actions/checkout@v4
        with:
          # rama concreta de fs
          ref: 2024.92
          fetch-depth: 0
          repository: 'NeoRazorX/facturascripts'

      - name: Clonar Plugin ${{ env.NOMBRE_PLUGIN }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: Plugins/${{ env.NOMBRE_PLUGIN }}

      - name: Clonar fsmaker
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: fsmaker

      - name: Cache de dependencias de Composer
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/files
          key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-${{ runner.os }}-${{ matrix.php-version }}-
            composer-${{ runner.os }}-

      - name: Instalar dependencias de FacturaScripts
        run: |
          mkdir -p MyFiles
          touch MyFiles/plugins.json
          composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: Instalar dependencias del plugin
        run: |
          cd Plugins/${{ env.NOMBRE_PLUGIN }}
          composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader
          cd ../..

      - name: Instalar dependencias de fsmaker
        run: |
          cd fsmaker
          composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader
          cd ..

      - name: Crear archivo de configuración
        run: echo "<?php
          define('FS_COOKIES_EXPIRE', 31536000);
          define('FS_ROUTE', '');
          define('FS_DB_TYPE', 'mysql');
          define('FS_DB_HOST', '127.0.0.1');
          define('FS_DB_PORT', 3306);
          define('FS_DB_NAME', 'facturascripts');
          define('FS_DB_USER', 'root');
          define('FS_DB_PASS', 'root');
          define('FS_DB_FOREIGN_KEYS', true);
          define('FS_DB_TYPE_CHECK', true);
          define('FS_MYSQL_CHARSET', 'utf8mb4');
          define('FS_MYSQL_COLLATE', 'utf8mb4_unicode_520_ci');
          define('FS_LANG', 'es_ES');
          define('FS_TIMEZONE', 'Europe/Madrid');
          define('FS_HIDDEN_PLUGINS', '');
          define('FS_DEBUG', true);
          define('FS_DISABLE_ADD_PLUGINS', false);
          define('FS_DISABLE_RM_PLUGINS', false);" > config.php

      - name: Ejecutar tests
        run: |
          cd Plugins/${{ env.NOMBRE_PLUGIN }}
          php ../../fsmaker/fsmaker.php run-tests ../../
          cd ../..

      - name: Mostrar logs en caso de fallo
        if: failure()
        run: |
          echo "=== Logs de la base de datos ==="
            docker logs $(docker ps -q --filter ancestor=mariadb:11) || true